import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import Navbar from "@/components/layout/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div className="flex h-screen overflow-hidden">

          <Sidebar />

          {/* Content Area */}
          <div className="flex flex-1 flex-col overflow-hidden">
            <Navbar />
            <main className="flex-1 bg-gray-50 p-4 sm:p-6 overflow-y-auto">
              {children}
            </main>
          </div>

        </div>
      </body>
    </html>
  );
}
